@startuml
'https://plantuml.com/class-diagram

class Supermercado {
    - ID
    - nombre
    - ubicacion
    - numeroTelefono
    - trabajadores
    - abierto

    + cerrarAbrirTienda
    + contratarPersonal
}

class Producto{
- ID
- marca
- tipo
- precio
- cantidad

+ cambiarPrecio
+ aumentarCantidad
}

class Empleado{
- ID
- cedula
- nombre
- puesto
- salario

+ cambiarSalario
+cambiarPuesto
}

class Caja{
- numeroCaja
- encargadoCaja
- tipoCaja
- cajaAbierta

+ cambioTurno
+ abrirCerrarCaja
}

enum tipo {
Lacteo
CanastaBasica
Vegetal
Fruta
Carne
}

enum tipoCaja {
cajaRapida
cajaConvencional
}

tipo -> Producto
tipoCaja -> Caja
@enduml